### ISSUE TITLE
Reconsider comment support

### ISSUE THREAD

**Issue by jacobdufault** [atom/language-json#28]
While it might not be in the spec, lots and lots of JSON is hand-written with comment support - take [chrome extension manifests](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/test/data/extensions/tray_cast/manifest.json&l=1), for example.

From a usability perspective, it makes sense to have support for comments. I don't see any downsides, but there are definite positives.

Would a PR to add comment support be accepted?

**Comment by kevinsawicki** [comment]
> Would a PR to add comment support be accepted?

I would be open to it, themes could still highlight as errors if they choose and it could be overridden as well in the `~/.atom/styles.less` file.

**Comment by pchaigno** [comment]
@jacobdufault Are you working on this?

**Comment by mnquintana** [comment]
I think @clintwood was working on this in https://github.com/atom/language-json/pull/29

**Comment by slang800** [comment]
> I don't see any downsides - @jacobdufault 

If only to play the devil's advocate, I see a major downside. The definition for JSON is as a data interchange format and it [intentionally doesn't support comments](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr). It's a rigid spec and anything that _does_ have comments is not JSON. Furthermore, calling a language that does support comments "JSON" is confusing, misleading, and flies in the face of the all the work that has been done to ensure standardization.

Anything that does not follow the syntax described in [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) should be displayed an an error within Atom because it will also be an error when it is processed as JSON by any other tool. This includes Chrome Extension Manifests - they are not vaid JSON if they have comments in them and anyone who says otherwise hasn't understood the spec.

If you _do_ want comments, then at least call your new language something different like [JSON5](http://json5.org/) did, rather than trying to fragment a working standard.

**Comment by 50Wliu** [comment]
See https://github.com/atom/language-json/pull/29#issuecomment-272520942 for reasoning and a solution if you do want comments.
