### ISSUE TITLE
N-level syntax highlighting

### ISSUE THREAD

**Issue by occurr** [atom/language-json#58]
n-level syntax highlighting is a great feature when reading JSON. Being able to see the nesting levels of keys makes reading large JSON significantly easier. 

For example, sublime's material theme looks like this :: 
![b2b540d6-8342-11e6-803b-3c26041c19e7](https://cloud.githubusercontent.com/assets/9969763/25778757/9718dcc8-32bc-11e7-8fe2-eb399db45aac.png)

Unfortunately, themes in atom can't add this due to a lack of current JSON grammars to support it. 

Is this a possible feature language-json could support via classes such as `.nesting.level{number}`?

**Comment by bpartridge** [comment]
I mean, it's not exactly what you want, but presuming your indentation is consistent, you can certainly condition on that, since the indent guides are (currently) sibling nodes.

<img width="279" alt="screenshot 2017-05-17 11 49 56" src="https://cloud.githubusercontent.com/assets/20748/26163244/1340406a-3af7-11e7-8f9d-b736203ccaeb.png">

**Comment by bpartridge** [comment]
Actually just built it for myself! Play with the color line however you want.

```
.syntax--dictionary.syntax--json {
  .loop(@counter) when (@counter >= 0) {
    .loop(@counter - 1);
    .leading-whitespace:nth-child(0n+@{counter}) + .syntax--key .syntax--string {
      // color: lighten(#2aa198, (@counter * 5%));
      color: hsl((@counter * 20), 50%, 40%);
    }
  }
  .loop(10);
}
```

**Comment by 50Wliu** [comment]
:heart: @bpartridge.  I was going to suggest something like that, but didn't know how to keep it compact.  Had no idea Less was this powerful!
